{
 "title": "Full Server Status",
 "description": "Simplify server monitoring with our Full Server Status dashboard. Track important metrics such as CPU and memory utilization, disk space usage, network traffic, and more in a single view.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk",
    "query": {
     "query": "query_result(node_disk_info{job=\"$job\",instance=\"$instance\"} or windows_logical_disk_size_bytes{job=\"$job\",instance=\"$instance\"})"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "query_result(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\"} or windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_memory_physical_total_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 16, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\",instance=\"$instance\"} - node_boot_time_seconds{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - windows_system_boot_time_timestamp{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_cpu_logical_processor{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"$job\",instance=\"$instance\"}\n",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "windows_os_hostname{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Problems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - ((windows_memory_physical_free_bytes{instance=\"$instance\",job=\"$job\"} * 100) / windows_memory_physical_free_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 - ((node_memory_MemAvailable_bytes{job=\"$job\",instance=\"$instance\"} * 100) / node_memory_MemTotal_bytes{job=\"$job\",instance=\"$instance\"})) or (100 - ((windows_os_physical_memory_free_bytes{instance=\"$instance\",job=\"$job\"} * 100) / windows_cs_physical_memory_bytes{instance=\"$instance\",job=\"$job\"}))",
     "legendFormat": "Memory utilization"
    },
    {
     "expr": "((sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}[$__rate_interval])))) * 100) or ((sum by(instance) (irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100)",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(instance) (irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU iowait time",
   "type": "stat",
   "description": "Amount of time the CPU has been waiting for I/O to complete.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$job\",instance=\"$instance\",mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(windows_cpu_time_total{job=\"$job\",instance=\"$instance\",mode=\"dpc\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_system_processes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem (Space utilization %)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{job=\"$job\",instance=\"$instance\"} / node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\"}) >= 1",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 * (1 - windows_logical_disk_free_bytes{job=\"$job\",instance=\"$instance\"} / windows_logical_disk_size_bytes{job=\"$job\",instance=\"$instance\"}) >= 1",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk drives ",
   "type": "stat",
   "description": "The amount of disk devices in the system",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_disk_info{job=\"$job\",instance=\"$instance\"}) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(windows_logical_disk_info{job=\"$job\",instance=\"$instance\"}) by (device_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logged in Users",
   "type": "stat",
   "description": "Number of users who are currently logged in",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_logind_sessions{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(go_info{job=\"$job\", instance=\"$instance\", status=~\"interactive|remote_interactive\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk $diskdevices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "diskdevices" },
  {
   "title": "$diskdevices (bits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
   "repeat": "Disk",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(irate(node_disk_written_bytes_total{instance=\"$instance\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) or (irate(windows_logical_disk_write_bytes_total{instance=\"$instance\",job=\"$job\",volume=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "writes"
    },
    {
     "expr": "(irate(node_disk_read_bytes_total{instance=\"$instance\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) or (irate(windows_logical_disk_read_bytes_total{instance=\"$instance\",job=\"$job\",volume=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "$diskdevices (I/O usage)",
   "type": "gauge",
   "description": "This item is the percentage of elapsed time that the selected disk drive was busy servicing read or writes requests.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 21 },
   "repeat": "Disk",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_min(1 - irate(windows_logical_disk_idle_seconds_total{instance=\"$instance\",job=\"$job\",volume=~\"$diskdevices\"}[$__rate_interval]), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$diskdevices (space)",
   "type": "timeseries",
   "description": "Used storage in Bytes",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "repeat": "Filesystem",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(avg by (device) (node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\",device=\"$diskdevices\"})) - (avg by (device) (node_filesystem_free_bytes{job=\"$job\",instance=\"$instance\",device=\"$diskdevices\"})) or (windows_logical_disk_size_bytes{job=\"$job\",instance=\"$instance\",volume=\"$diskdevices\"}) - (windows_logical_disk_free_bytes{job=\"$job\",instance=\"$instance\",volume=\"$diskdevices\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "(avg by (device) (node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\",device=\"$diskdevices\"})) or (windows_logical_disk_size_bytes{job=\"$job\",instance=\"$instance\",volume=\"$diskdevices\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Network $network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "network" },
  {
   "title": "(IN) $network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 49 },
   "repeat": "Network",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 49 },
   "repeat": "Network",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8) or (irate(windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "receive"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8) or (irate(windows_net_bytes_sent_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "transmit"
    },
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(OUT) $network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 49 },
   "repeat": "Network",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Problems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } }
 ]
}