{
 "title": "Microsoft SQL Server",
 "description": "Works with and awaragi/prometheus-mssql-exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(mssql_instance_local_time, job)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(mssql_connections,database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Job：Server resource overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mssql_instance_local_time{job=~\"$Job\"}*1000"
    },
    {
     "expr": "mssql_total_physical_memory_kb{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_available_physical_memory_kb{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_total_page_file_kb{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_available_page_file_kb{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_page_fault_count{job=~\"$Job\"}-0",
     "legendFormat": "Total page faults"
    },
    {
     "expr": "mssql_batch_requests{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_page_life_expectancy{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_deadlocks{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_user_errors{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_kill_connection_errors{job=~\"$Job\"}-0"
    }
   ]
  },
  {
   "title": "Transacciones/sec por DB",
   "type": "gauge",
   "description": "Monitoreo de carga de cada base de datos.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_transactions", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "SQL SATUS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL BLOQUEOS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_deadlocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL DATABASE STATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_database_state{database=\"change_me\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL MEMORIA USADA",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_memory_utilization_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL LOGS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_log_growths{database=\"change_me\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FICHEROS DE LOGS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_database_filesize / 1024 / 1024",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current database connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_connections{}", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "DB Log growth since last restart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mssql_log_growths", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mssql_io_stall_total{job=~\"$Job\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database I/O wait of stall detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mssql_io_stall{database=~\"^$database\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}